EGNO:
  num_timesteps: 10
  model_params:
    n_layers: 4
    hidden_nf: 64
    flat: false
    norm: false
    time_emb_dim: 32
    in_node_nf: 2
    in_edge_nf: 2
    with_v: True
    num_modes: 2 # 5
    time_emb_dim: 32

  training_params:
    lr: 1e-4
    weight_decay: 1e-8


SEGNO:
  num_timesteps: 10
  model_params:
    in_node_nf: 1
    in_edge_nf: 2 # distance and {mass, charge}
    hidden_nf: 64
    n_layers: 8
    recurrent: True
    norm_diff: False
    tanh: False

  training_params:
    lr: 5e-3
    weight_decay: 1e-12

  other_params:
    nbody_name: nbody_small